/** Predefined anonymization rule templates for data privacy compliance. */
export const ANONYMIZATION_TEMPLATES = [
  {
    id: 'tpl-gdpr-standard',
    name: 'GDPR Standard',
    description: 'Standard GDPR compliance: anonymize personal data fields across common Salesforce objects.',
    complianceFramework: 'gdpr',
    rules: [
      { fieldPattern: 'Contact.FirstName', ruleType: 'fake', description: 'Replace with fake first name.' },
      { fieldPattern: 'Contact.LastName', ruleType: 'fake', description: 'Replace with fake last name.' },
      { fieldPattern: 'Contact.Email', ruleType: 'fake', description: 'Replace with fake email address.' },
      { fieldPattern: 'Contact.Phone', ruleType: 'mask', description: 'Mask phone number (keep last 4 digits).' },
      { fieldPattern: 'Contact.MailingStreet', ruleType: 'fake', description: 'Replace with fake street address.' },
      { fieldPattern: 'Contact.MailingCity', ruleType: 'fake', description: 'Replace with fake city.' },
      { fieldPattern: 'Contact.MailingPostalCode', ruleType: 'mask', description: 'Mask postal code.' },
      { fieldPattern: 'Lead.FirstName', ruleType: 'fake', description: 'Replace with fake first name.' },
      { fieldPattern: 'Lead.LastName', ruleType: 'fake', description: 'Replace with fake last name.' },
      { fieldPattern: 'Lead.Email', ruleType: 'fake', description: 'Replace with fake email address.' },
      { fieldPattern: 'Lead.Phone', ruleType: 'mask', description: 'Mask phone number.' },
      { fieldPattern: 'Lead.Street', ruleType: 'fake', description: 'Replace with fake street address.' },
      { fieldPattern: 'Account.BillingStreet', ruleType: 'fake', description: 'Replace with fake address.' },
      { fieldPattern: 'Account.Phone', ruleType: 'mask', description: 'Mask phone number.' },
    ],
  },
  {
    id: 'tpl-ccpa-california',
    name: 'CCPA California',
    description: 'CCPA compliance: anonymize consumer personal information per California privacy regulations.',
    complianceFramework: 'ccpa',
    rules: [
      { fieldPattern: 'Contact.FirstName', ruleType: 'fake', description: 'Replace consumer first name.' },
      { fieldPattern: 'Contact.LastName', ruleType: 'fake', description: 'Replace consumer last name.' },
      { fieldPattern: 'Contact.Email', ruleType: 'hash', description: 'Hash email for pseudonymization.' },
      { fieldPattern: 'Contact.Phone', ruleType: 'nullify', description: 'Nullify phone number.' },
      { fieldPattern: 'Contact.MailingStreet', ruleType: 'nullify', description: 'Nullify street address.' },
      { fieldPattern: 'Contact.MailingCity', ruleType: 'nullify', description: 'Nullify city.' },
      { fieldPattern: 'Contact.MailingPostalCode', ruleType: 'nullify', description: 'Nullify postal code.' },
      { fieldPattern: 'Contact.Birthdate', ruleType: 'nullify', description: 'Remove date of birth.' },
      { fieldPattern: 'Lead.Email', ruleType: 'hash', description: 'Hash email for pseudonymization.' },
      { fieldPattern: 'Lead.Phone', ruleType: 'nullify', description: 'Nullify phone number.' },
    ],
  },
  {
    id: 'tpl-hipaa-health',
    name: 'HIPAA Health Data',
    description: 'HIPAA compliance: de-identify protected health information (PHI) in healthcare Salesforce orgs.',
    complianceFramework: 'hipaa',
    rules: [
      { fieldPattern: 'Contact.FirstName', ruleType: 'fake', description: 'Replace patient first name.' },
      { fieldPattern: 'Contact.LastName', ruleType: 'fake', description: 'Replace patient last name.' },
      { fieldPattern: 'Contact.Email', ruleType: 'hash', description: 'Hash email address.' },
      { fieldPattern: 'Contact.Phone', ruleType: 'mask', description: 'Mask phone number.' },
      { fieldPattern: 'Contact.Birthdate', ruleType: 'nullify', description: 'Remove date of birth (PHI).' },
      { fieldPattern: 'Contact.MailingStreet', ruleType: 'nullify', description: 'Remove address (PHI).' },
      { fieldPattern: 'Contact.MailingCity', ruleType: 'nullify', description: 'Remove city (PHI).' },
      { fieldPattern: 'Contact.MailingState', ruleType: 'nullify', description: 'Remove state (PHI).' },
      { fieldPattern: 'Contact.MailingPostalCode', ruleType: 'truncate', description: 'Truncate to first 3 digits.' },
      { fieldPattern: 'Account.Name', ruleType: 'fake', description: 'Replace facility name.' },
      { fieldPattern: 'Account.Phone', ruleType: 'mask', description: 'Mask facility phone.' },
    ],
  },
  {
    id: 'tpl-sandbox-scrub',
    name: 'Sandbox Data Scrub',
    description: 'General-purpose sandbox data scrubbing: mask all PII for safe development use.',
    complianceFramework: 'custom',
    rules: [
      { fieldPattern: 'Contact.FirstName', ruleType: 'fake', description: 'Fake first name.' },
      { fieldPattern: 'Contact.LastName', ruleType: 'fake', description: 'Fake last name.' },
      { fieldPattern: 'Contact.Email', ruleType: 'preserve_format', description: 'Replace keeping email format.' },
      { fieldPattern: 'Contact.Phone', ruleType: 'preserve_format', description: 'Replace keeping phone format.' },
      { fieldPattern: 'Lead.FirstName', ruleType: 'fake', description: 'Fake first name.' },
      { fieldPattern: 'Lead.LastName', ruleType: 'fake', description: 'Fake last name.' },
      { fieldPattern: 'Lead.Email', ruleType: 'preserve_format', description: 'Replace keeping email format.' },
      { fieldPattern: 'Lead.Company', ruleType: 'fake', description: 'Fake company name.' },
      { fieldPattern: 'Account.Name', ruleType: 'fake', description: 'Fake account name.' },
      { fieldPattern: 'Account.Website', ruleType: 'constant', description: 'Replace with placeholder URL.' },
      { fieldPattern: 'Opportunity.Name', ruleType: 'fake', description: 'Fake opportunity name.' },
    ],
  },
] as const;
