/** AI provider function type for generating text completions. */
export type AIProvider = (prompt: string) => Promise<string>;

/** Suggestion impact level. */
export type SuggestionImpact = 'low' | 'medium' | 'high';

/** A contextual suggestion generated by the engine. */
export interface Suggestion {
  title: string;
  description: string;
  impact: SuggestionImpact;
  confidence: number;
  action: string;
  dismissable: boolean;
  module: string;
}

/** Built-in rule definition for module-specific suggestions. */
interface ModuleRule {
  title: string;
  description: string;
  impact: SuggestionImpact;
  confidence: number;
  action: string;
  condition: (context: Record<string, unknown>) => boolean;
}

/** Built-in rules keyed by module name. */
const MODULE_RULES: Record<string, ModuleRule[]> = {
  compare: [
    {
      title: 'Optimize deployment order',
      description: 'Deploy parent objects before children to avoid reference failures.',
      impact: 'high',
      confidence: 0.9,
      action: 'reorder_deployment',
      condition: (ctx) => Array.isArray(ctx['objects']) && (ctx['objects'] as unknown[]).length > 1,
    },
    {
      title: 'Estimate impact before deploying',
      description: 'Run a dry-run comparison to measure how many records will be affected.',
      impact: 'medium',
      confidence: 0.85,
      action: 'dry_run',
      condition: (ctx) => ctx['hasChanges'] === true,
    },
  ],
  seed: [
    {
      title: 'Improve template based on errors',
      description: 'Adjust field generation rules to reduce validation errors on insert.',
      impact: 'high',
      confidence: 0.8,
      action: 'fix_template',
      condition: (ctx) => typeof ctx['errorCount'] === 'number' && (ctx['errorCount'] as number) > 0,
    },
    {
      title: 'Add required field defaults',
      description: 'Some required fields have no generation rule configured.',
      impact: 'medium',
      confidence: 0.95,
      action: 'add_defaults',
      condition: (ctx) =>
        Array.isArray(ctx['missingRequired']) && (ctx['missingRequired'] as unknown[]).length > 0,
    },
  ],
  sync: [
    {
      title: 'Increase batch size',
      description: 'Current batch size is low relative to record count. Increasing it may improve throughput.',
      impact: 'medium',
      confidence: 0.75,
      action: 'increase_batch',
      condition: (ctx) =>
        typeof ctx['batchSize'] === 'number' &&
        typeof ctx['recordCount'] === 'number' &&
        (ctx['batchSize'] as number) < 200 &&
        (ctx['recordCount'] as number) > 2000,
    },
    {
      title: 'Review field mapping',
      description: 'Some mapped fields have type mismatches between source and target.',
      impact: 'high',
      confidence: 0.85,
      action: 'review_mapping',
      condition: (ctx) => typeof ctx['typeMismatches'] === 'number' && (ctx['typeMismatches'] as number) > 0,
    },
  ],
  monitor: [
    {
      title: 'Address critical alerts',
      description: 'There are unresolved critical alerts that require immediate attention.',
      impact: 'high',
      confidence: 0.95,
      action: 'resolve_alerts',
      condition: (ctx) => typeof ctx['criticalAlerts'] === 'number' && (ctx['criticalAlerts'] as number) > 0,
    },
    {
      title: 'Schedule off-peak operations',
      description: 'Heavy operations are running during peak hours. Consider rescheduling.',
      impact: 'medium',
      confidence: 0.7,
      action: 'reschedule',
      condition: (ctx) => ctx['peakHours'] === true,
    },
  ],
  dataops: [
    {
      title: 'Add anonymization rules',
      description: 'Sensitive fields detected without anonymization rules configured.',
      impact: 'high',
      confidence: 0.9,
      action: 'add_anonymization',
      condition: (ctx) =>
        Array.isArray(ctx['sensitiveFields']) && (ctx['sensitiveFields'] as unknown[]).length > 0,
    },
    {
      title: 'Enable audit logging',
      description: 'Data operations are running without audit logging enabled.',
      impact: 'medium',
      confidence: 0.85,
      action: 'enable_audit',
      condition: (ctx) => ctx['auditEnabled'] === false,
    },
  ],
};

/**
 * Contextual suggestions engine that generates module-aware
 * recommendations using built-in rules and optional AI fallback.
 */
export class SmartSuggestions {
  private readonly dismissed: Set<string> = new Set();
  private readonly provider: AIProvider | undefined;

  /**
   * @param provider - Optional AI provider for complex suggestions
   */
  constructor(provider?: AIProvider) {
    this.provider = provider;
  }

  /**
   * Generate contextual suggestions for a given module.
   * Applies built-in rules first, then falls back to AI for complex analysis.
   * @param module - The module name (compare, seed, sync, monitor, dataops)
   * @param context - Key-value context from the module's current state
   * @returns Array of applicable suggestions, excluding dismissed ones
   */
  async suggest(module: string, context: Record<string, unknown>): Promise<Suggestion[]> {
    const suggestions: Suggestion[] = [];

    const rules = MODULE_RULES[module];
    if (rules) {
      for (const rule of rules) {
        if (rule.condition(context) && !this.dismissed.has(rule.title)) {
          suggestions.push({
            title: rule.title,
            description: rule.description,
            impact: rule.impact,
            confidence: rule.confidence,
            action: rule.action,
            dismissable: true,
            module,
          });
        }
      }
    }

    if (suggestions.length === 0 && this.provider) {
      const aiSuggestions = await this.fetchAISuggestions(module, context);
      for (const s of aiSuggestions) {
        if (!this.dismissed.has(s.title)) {
          suggestions.push(s);
        }
      }
    }

    return suggestions;
  }

  /**
   * Dismiss a suggestion by title so it won't appear again.
   * @param title - The suggestion title to dismiss
   */
  dismissSuggestion(title: string): void {
    this.dismissed.add(title);
  }

  /**
   * Get all dismissed suggestion titles.
   * @returns Array of dismissed suggestion titles
   */
  getDismissed(): string[] {
    return Array.from(this.dismissed);
  }

  /**
   * Clear all dismissed suggestions.
   */
  clearDismissed(): void {
    this.dismissed.clear();
  }

  private async fetchAISuggestions(
    module: string,
    context: Record<string, unknown>,
  ): Promise<Suggestion[]> {
    if (!this.provider) return [];

    const prompt = `Analyze the following context for the "${module}" module and suggest improvements.\nContext: ${JSON.stringify(context)}\nReturn a JSON array of objects with: title, description, impact (low|medium|high), confidence (0-1), action.`;

    const response = await this.provider(prompt);

    try {
      const parsed: unknown = JSON.parse(response);
      if (!Array.isArray(parsed)) return [];

      return parsed
        .filter(
          (item): item is Record<string, unknown> =>
            typeof item === 'object' &&
            item !== null &&
            typeof (item as Record<string, unknown>)['title'] === 'string' &&
            typeof (item as Record<string, unknown>)['description'] === 'string',
        )
        .map((item) => ({
          title: item['title'] as string,
          description: item['description'] as string,
          impact: isValidImpact(item['impact']) ? item['impact'] : 'low',
          confidence: typeof item['confidence'] === 'number' ? item['confidence'] : 0.5,
          action: typeof item['action'] === 'string' ? item['action'] : 'review',
          dismissable: true,
          module,
        }));
    } catch {
      return [];
    }
  }
}

/**
 * Type guard for valid impact values.
 * @param value - The value to check
 * @returns True if value is a valid SuggestionImpact
 */
function isValidImpact(value: unknown): value is SuggestionImpact {
  return value === 'low' || value === 'medium' || value === 'high';
}
