#!/usr/bin/env tsx
/**
 * sandforge-seed — headless Seed runner.
 *
 * The third of these, for the same reason as the first two: running the
 * product against a real org is the only thing that has ever found a defect in
 * it. Forge gave up eleven that way and Sync three, none of which any test,
 * mutation run or workflow had seen.
 *
 * It drives the same `SeedOrchestrator` the panel drives, with the same
 * validator, plan builder, field mapper and reference linker, and writes
 * through the same REST batching. What it leaves out is what the panel adds
 * around a run: progress posted to a webview, the AI field generator (the
 * faker fallback covers every rule on its own) and grappe partitioning.
 *
 * Usage:
 *   pnpm exec tsx packages/extension/cli/sandforge-seed.ts \
 *     --target TGT --template prebuilt-minimal-demo
 *   pnpm exec tsx packages/extension/cli/sandforge-seed.ts \
 *     --target TGT --object Account:3 --object Contact:1 \
 *     --relation Contact.AccountId=Account --per-parent 3
 *
 * Run from the repository root of a checkout, after pnpm install and
 * pnpm build:shared.
 */

import type { SeedRelation, SeedTemplate } from '@sandforge/shared';
import {
  PREBUILT_SEED_TEMPLATES,
  SEED_RELATION_LIMITS,
  describedFieldRule,
  duplicateRuleHeaders,
  integerDigitsOf,
  plannedChildCount,
} from '@sandforge/shared';
import { loadOrg, makeConn } from './sfSession.js';
import { SeedOrchestrator } from '../src/modules/seed/SeedOrchestrator.js';
import { SeedValidator } from '../src/modules/seed/SeedValidator.js';
import { DataPlanBuilder } from '../src/modules/seed/DataPlanBuilder.js';
import { FieldMapper } from '../src/modules/seed/FieldMapper.js';
import { ReferenceLinker } from '../src/modules/seed/ReferenceLinker.js';
import { FakerFallback } from '../src/modules/seed/FakerFallback.js';
import { AIDataGenerator } from '../src/modules/seed/AIDataGenerator.js';
import { readExistingParentIds } from '../src/modules/seed/existingParents.js';

const HELP = `sandforge-seed — fill an org from a seed template, without the editor.

Usage:
  pnpm exec tsx packages/extension/cli/sandforge-seed.ts \\
    --target <alias> [--template <id> | --object <ApiName>:<count>] [options]

Required:
  --target <alias>       sf CLI alias of the org to fill

One of:
  --template <id>        a built-in template; --list-templates names them
  --object <Api>:<n>     an object and how many rows; repeat for more, in
                         insert order. Fields are generated by the faker.

Options:
  --list-templates       name the built-in templates, then stop
  --batch-size <n>       records per write call            (default: 200)
  --dry-run              build and map, write nothing      (default: off)
  --json                 emit the run summary as JSON      (default: off)
  --help                 this text

Relations (with --object; the options after a --relation apply to it):
  --relation <Child>.<Lookup>=<Parent>
                         fill a lookup of one --object from a parent object's
                         records. The child gets the records the relation
                         plans, in place of the count given with --object
  --per-parent <n>       exactly n children per parent     (default: 1)
  --between <min>-<max>  a whole number from min to max per parent, at random
  --ratio <r>            r children per parent on average; 0.5 gives a child
                         to every other parent
  --existing             draw the parents from records already in the org
                         instead of the ones this run writes
  --where <condition>    only records meeting this SOQL WHERE condition
                         (implies --existing)
  --parent-limit <n>     the most records --existing reads (default: 10)

Exit codes: 0 the run finished (read the summary for per-object failures),
1 the run could not be started, 2 a bad command line.
`;

/** Everything the command line settled. */
interface CliArgs {
  target: string;
  templateId?: string;
  /** In insert order; a relation's child carries the count the relation plans. */
  objects: Array<{ objectApiName: string; recordCount: number }>;
  relations: SeedRelation[];
  batchSize: number;
  dryRun: boolean;
  json: boolean;
}

/** SObject API name — letter-prefixed, alphanumeric and underscore. */
const API_NAME_RE = /^[A-Za-z][A-Za-z0-9_]{0,79}$/;

/** `Child.Lookup=Parent`, each part an API name. */
const RELATION_RE =
  /^([A-Za-z][A-Za-z0-9_]{0,79})\.([A-Za-z][A-Za-z0-9_]{0,79})=([A-Za-z][A-Za-z0-9_]{0,79})$/;

/** How many existing parents a relation reads when --parent-limit does not say. */
const DEFAULT_PARENT_LIMIT = 10;

/**
 * The relations on the command line, each with the options that follow it up
 * to the next --relation.
 */
function parseRelations(args: string[], refuse: (line: string) => never): SeedRelation[] {
  const relations: SeedRelation[] = [];
  const most = SEED_RELATION_LIMITS.maxPerParent;
  const wholeIn = (raw: string | undefined, min: number, max: number, flag: string): number => {
    const value = Number(raw);
    if (!Number.isInteger(value) || value < min || value > max) {
      refuse(`${flag} takes a whole number from ${min} to ${max}, not "${raw ?? ''}".`);
    }
    return value;
  };
  const existing = (
    relation: SeedRelation,
  ): Extract<SeedRelation['parents'], { kind: 'existing' }> => {
    if (relation.parents.kind !== 'existing') {
      relation.parents = { kind: 'existing', limit: DEFAULT_PARENT_LIMIT };
    }
    return relation.parents;
  };

  for (let i = 0; i < args.length; i++) {
    const flag = args[i];
    const value = args[i + 1];
    if (flag === '--relation') {
      const match = RELATION_RE.exec(value ?? '');
      if (!match) refuse(`--relation wants "Child.Lookup=Parent", not "${value ?? ''}".`);
      const [, childObject, lookupField, parentObject] = match as RegExpExecArray;
      relations.push({
        childObject,
        lookupField,
        parentObject,
        parents: { kind: 'generated' },
        distribution: { mode: 'perParent', count: 1 },
      });
      i++;
      continue;
    }
    const isRelationOption = [
      '--per-parent',
      '--between',
      '--ratio',
      '--existing',
      '--where',
      '--parent-limit',
    ].includes(flag);
    if (!isRelationOption) continue;
    const current = relations.at(-1);
    if (!current) refuse(`${flag} applies to a relation: give --relation before it.`);
    const relation = current as SeedRelation;

    if (flag === '--existing') {
      existing(relation);
      continue;
    }
    i++;
    if (flag === '--per-parent') {
      relation.distribution = { mode: 'perParent', count: wholeIn(value, 1, most, flag) };
    } else if (flag === '--between') {
      const range = /^(\d+)-(\d+)$/.exec(value ?? '');
      if (!range) refuse(`--between wants "<min>-<max>", not "${value ?? ''}".`);
      const [, low, high] = range as RegExpExecArray;
      const min = wholeIn(low, 0, most, flag);
      const max = wholeIn(high, Math.max(1, min), most, flag);
      relation.distribution = { mode: 'range', min, max };
    } else if (flag === '--ratio') {
      const ratio = Number(value);
      if (!Number.isFinite(ratio) || ratio < SEED_RELATION_LIMITS.minRatio || ratio > most) {
        refuse(
          `--ratio takes a number from ${SEED_RELATION_LIMITS.minRatio} to ${most}, not "${value ?? ''}".`,
        );
      }
      relation.distribution = { mode: 'ratio', ratio };
    } else if (flag === '--where') {
      if (!value?.trim()) refuse('--where wants a SOQL condition.');
      existing(relation).where = value;
    } else {
      existing(relation).limit = wholeIn(value, 1, SEED_RELATION_LIMITS.maxExistingParents, flag);
    }
  }
  return relations;
}

/**
 * The objects with each relation's child counted the way the panel counts it:
 * the parents it will find — the parent object's count for records this run
 * writes, the bound for records read from the org — times what each receives.
 */
function countChildren(
  objects: CliArgs['objects'],
  relations: SeedRelation[],
  refuse: (line: string) => never,
): CliArgs['objects'] {
  const counted = objects.map((object) => ({ ...object }));
  for (const relation of relations) {
    const name = `${relation.childObject}.${relation.lookupField}`;
    const child = counted.find((object) => object.objectApiName === relation.childObject);
    if (!child) refuse(`--relation ${name}: give ${relation.childObject} with --object too.`);
    let parents: number;
    if (relation.parents.kind === 'existing') {
      parents = relation.parents.limit;
    } else {
      const parent = counted.find((object) => object.objectApiName === relation.parentObject);
      if (!parent || relation.parentObject === relation.childObject) {
        refuse(
          `--relation ${name}: the ${relation.parentObject} records this run writes cannot be the ` +
            `parents; give ${relation.parentObject} with --object, or add --existing.`,
        );
      }
      parents = (parent as { recordCount: number }).recordCount;
    }
    const planned = plannedChildCount(relation.distribution, parents);
    if (planned < 1) refuse(`--relation ${name} gives no parent a child: raise --ratio.`);
    (child as { recordCount: number }).recordCount = planned;
  }
  return counted;
}

/** Read the command line, or explain why it cannot be read. */
export function parseArgs(argv: string[]): CliArgs {
  const args = argv.slice(2);
  if (args.includes('--help') || args.includes('-h')) {
    process.stdout.write(HELP);
    process.exit(0);
  }
  if (args.includes('--list-templates')) {
    for (const template of PREBUILT_SEED_TEMPLATES) {
      process.stdout.write(
        `${template.id.padEnd(34)}${template.objects.length} object(s)  ${template.name}\n`,
      );
    }
    process.exit(0);
  }
  const get = (flag: string, fallback?: string): string | undefined => {
    const at = args.indexOf(flag);
    return at >= 0 && at + 1 < args.length ? args[at + 1] : fallback;
  };
  const refuse = (line: string): never => {
    process.stderr.write(`${line}\n`);
    process.exit(2);
  };
  const collect = (flag: string): string[] => {
    const out: string[] = [];
    for (let i = 0; i < args.length; i++) {
      if (args[i] === flag && i + 1 < args.length) out.push(args[i + 1]);
    }
    return out;
  };

  const target = get('--target');
  const templateId = get('--template');
  const rawObjects = collect('--object');
  if (!target) {
    process.stderr.write('Missing --target. Run with --help.\n');
    process.exit(2);
  }
  if (!templateId && rawObjects.length === 0) {
    process.stderr.write('Nothing to seed: give --template or --object. Run with --help.\n');
    process.exit(2);
  }
  if (templateId && rawObjects.length > 0) {
    // Two answers to "what should this write" is one too many.
    process.stderr.write('Give --template or --object, not both.\n');
    process.exit(2);
  }

  const objects = rawObjects.map((raw) => {
    const at = raw.lastIndexOf(':');
    const objectApiName = at > 0 ? raw.slice(0, at) : raw;
    const recordCount = at > 0 ? Number(raw.slice(at + 1)) : NaN;
    if (!API_NAME_RE.test(objectApiName)) {
      process.stderr.write(`Not an SObject API name: "${objectApiName}"\n`);
      process.exit(2);
    }
    if (!Number.isInteger(recordCount) || recordCount < 1 || recordCount > 100_000) {
      process.stderr.write(`--object wants "Name:<count>", not "${raw}".\n`);
      process.exit(2);
    }
    return { objectApiName, recordCount };
  });

  const batchSize = Number(get('--batch-size', '200') ?? '200');
  if (!Number.isInteger(batchSize) || batchSize < 1 || batchSize > 10_000) {
    process.stderr.write('--batch-size takes a whole number between 1 and 10000.\n');
    process.exit(2);
  }

  const relations = parseRelations(args, refuse);
  if (relations.length > 0 && templateId) {
    refuse('--relation goes with --object: a built-in template carries its own links.');
  }

  return {
    target,
    templateId,
    objects: countChildren(objects, relations, refuse),
    relations,
    batchSize,
    dryRun: args.includes('--dry-run'),
    json: args.includes('--json'),
  };
}

/** A built-in template by id, or `null` when the flags describe the objects. */
export function prebuiltTemplate(templateId: string | undefined): SeedTemplate | null {
  if (!templateId) return null;
  const found = PREBUILT_SEED_TEMPLATES.find((t) => t.id === templateId);
  if (!found) {
    const names = PREBUILT_SEED_TEMPLATES.map((t) => t.id).join(', ');
    process.stderr.write(`No template "${templateId}". There is: ${names}\n`);
    process.exit(2);
  }
  return found;
}

/**
 * The fields to fill for an object, and what to fill them with.
 *
 * An object with no field rules writes nothing — the validator refuses it now
 * — so `--object Name:count` has to name some. They come from the target's own
 * describe, through the same `describedFieldRule` the panel gives a field it
 * has just described, so what this writes is what the panel would write for
 * the same object: a text cut to the field's length, a number within its
 * digits, a percentage within 100. Picking the method alone, as this did,
 * drew numbers up to 1000 for a two-digit field, which the org refuses.
 *
 * Only what the platform insists on, plus `Name`: a seed is meant to make an
 * org usable, not to fill every column it has. A lookup is filled by a
 * relation the command line names, never by a rule of its own.
 */
export function rulesFromDescribe(
  fields: Array<{
    name: string;
    type: string;
    createable: boolean;
    nillable: boolean;
    defaultedOnCreate?: boolean;
    length?: number;
    precision?: number;
    scale?: number;
    digits?: number;
    picklistValues?: Array<{ value?: string | null; active?: boolean }>;
  }>,
): SeedTemplate['objects'][number]['fieldRules'] {
  const wanted = fields.filter(
    (f) => f.createable && (f.name === 'Name' || (!f.nillable && f.defaultedOnCreate !== true)),
  );
  const rules: SeedTemplate['objects'][number]['fieldRules'] = [];
  for (const field of wanted) {
    const rule = describedFieldRule({
      fieldApiName: field.name,
      type: field.type,
      picklistValues: (field.picklistValues ?? [])
        .filter((p) => p.active !== false && typeof p.value === 'string')
        .map((p) => p.value as string),
      referenceTo: [],
      length: field.length ?? 0,
      integerDigits: integerDigitsOf(field),
    });
    // Nothing to fill it with: the platform answers for the field.
    if (rule.ruleType === 'static' && rule.config.staticValue === undefined) continue;
    rules.push({
      fieldApiName: field.name,
      fieldType: field.type,
      ruleType: rule.ruleType,
      config: rule.config,
    });
  }
  return rules;
}

/** How a relation spreads its children, in words. */
export function describeDistribution(distribution: SeedRelation['distribution']): string {
  switch (distribution.mode) {
    case 'perParent':
      return `${distribution.count} per parent`;
    case 'range':
      return `${distribution.min} to ${distribution.max} per parent`;
    case 'ratio':
      return `${distribution.ratio} per parent on average`;
  }
}

/** Run one seed from the given command line; exported so its parsing can be tested. */
export async function main(argv: string[] = process.argv): Promise<void> {
  const t0 = Date.now();
  const args = parseArgs(argv);
  const log = (line: string): void => {
    if (!args.json) process.stdout.write(`${line}\n`);
  };

  log(`sandforge-seed  -> ${args.target}`);
  const conn = makeConn(await loadOrg(args.target));

  const now = new Date().toISOString();
  let template = prebuiltTemplate(args.templateId);
  for (const relation of args.relations) {
    const parents =
      relation.parents.kind === 'generated'
        ? `the ${relation.parentObject} records this run writes`
        : `at most ${relation.parents.limit} ${relation.parentObject} records already in the org` +
          (relation.parents.where ? ` where ${relation.parents.where}` : '');
    const count = args.objects.find((o) => o.objectApiName === relation.childObject)?.recordCount;
    log(
      `  relation ${relation.childObject}.${relation.lookupField}: up to ${count} record(s), ` +
        `${describeDistribution(relation.distribution)}, over ${parents}`,
    );
  }
  if (!template) {
    const objects: SeedTemplate['objects'] = [];
    for (const [index, spec] of args.objects.entries()) {
      const described = await conn.sobject(spec.objectApiName).describe();
      const rules = rulesFromDescribe(
        described.fields as unknown as Parameters<typeof rulesFromDescribe>[0],
      );
      log(`  ${spec.objectApiName}: ${rules.map((r) => r.fieldApiName).join(', ') || '(none)'}`);
      objects.push({
        objectApiName: spec.objectApiName,
        recordCount: spec.recordCount,
        fieldRules: rules,
        excludedFields: [],
        insertOrder: index,
        batchSize: args.batchSize,
      });
    }
    template = {
      id: `cli-${Date.now()}`,
      name: 'sandforge-seed',
      description: 'Headless run',
      version: 1,
      strategy: 'faker',
      objects,
      ...(args.relations.length > 0 ? { relations: args.relations } : {}),
      tags: ['cli'],
      createdAt: now,
      updatedAt: now,
    };
  }
  log(`template: ${template.name} (${template.objects.length} object(s))`);

  const insert = async (
    _orgId: string,
    objectApiName: string,
    records: Record<string, unknown>[],
    batchSize: number,
  ): Promise<{ successIds: string[]; errors: string[] }> => {
    if (args.dryRun) {
      log(`  [dry-run] ${objectApiName}: ${records.length} record(s)`);
      return { successIds: records.map((_, i) => `dry-${i}`), errors: [] };
    }
    const successIds: string[] = [];
    const errors: string[] = [];
    for (let at = 0; at < records.length; at += batchSize) {
      const batch = records.slice(at, at + batchSize);
      const written = (await conn
        .sobject(objectApiName)
        .create(batch, { headers: duplicateRuleHeaders(true) })) as Array<{
        success: boolean;
        id?: string;
        errors?: Array<{ message: string }>;
      }>;
      for (const one of written) {
        if (one.success && one.id) successIds.push(one.id);
        else errors.push(one.errors?.[0]?.message ?? 'Unknown insert error');
      }
    }
    log(`  ${objectApiName}: ${successIds.length} written, ${errors.length} refused`);
    return { successIds, errors };
  };

  const creatableByObject = new Map<string, ReadonlySet<string>>();

  const orchestrator = new SeedOrchestrator({
    validator: new SeedValidator(),
    // A relation reads its parents from the org when told to, dry run or not:
    // a read writes nothing.
    readExistingParentIds: (objectApiName, where, limit) =>
      readExistingParentIds(conn, objectApiName, where, limit),
    describeCreateableFields: async (objectApiName) => {
      const cached = creatableByObject.get(objectApiName);
      if (cached) return cached;
      const described = await conn.sobject(objectApiName).describe();
      const names = new Set(described.fields.filter((f) => f.createable).map((f) => f.name));
      creatableByObject.set(objectApiName, names);
      return names;
    },
    planBuilder: new DataPlanBuilder(),
    // An AI generator that refuses. The faker answers every rule the templates
    // here carry, and a run that needs an API key is a run nobody can
    // reproduce — but a template written elsewhere may carry an `ai` rule, and
    // silently filling those with something else would be worse than saying so.
    fieldMapper: new FieldMapper({
      aiGenerator: new AIDataGenerator(() => {
        throw new Error(
          'This template has an AI field rule. sandforge-seed runs without an ' +
            'AI key: use the panel for it, or replace the rule with a faker one.',
        );
      }),
      fakerFallback: new FakerFallback(),
    }),
    referenceLinker: new ReferenceLinker(),
    insert,
    generateId: () => `cli-${Math.random().toString(36).slice(2)}`,
    now: () => new Date().toISOString(),
  });

  log(args.dryRun ? '\nexecuting… (DRY-RUN)' : '\nexecuting… (REAL)');
  const result = await orchestrator.execute(template, args.target);
  const elapsedMs = Date.now() - t0;

  if (args.json) {
    process.stdout.write(
      `${JSON.stringify({ tool: 'sandforge-seed', target: args.target, dryRun: args.dryRun, result, elapsedMs }, null, 2)}\n`,
    );
    return;
  }

  log(`\nstatus:  ${String((result as { status?: string }).status ?? 'unknown')}`);
  log(`created: ${String((result as { totalRecordsCreated?: number }).totalRecordsCreated ?? 0)}`);
  for (const entry of result.objectResults ?? []) {
    log(`  ${entry.objectApiName}: ${entry.recordsCreated} created, ${entry.recordsFailed} failed`);
    for (const error of (entry.errors ?? []).slice(0, 3)) log(`      ${error}`);
  }
  log(`\ndone in ${elapsedMs}ms`);
}

// `tsx` runs this file directly; the check keeps it silent under test.
if (process.argv[1]?.includes('sandforge-seed')) {
  main().catch((err: unknown) => {
    process.stderr.write(`${err instanceof Error ? err.message : String(err)}\n`);
    process.exit(1);
  });
}
