#!/usr/bin/env tsx
/**
 * sandforge-seed — headless Seed runner.
 *
 * The third of these, for the same reason as the first two: running the
 * product against a real org is the only thing that has ever found a defect in
 * it. Forge gave up eleven that way and Sync three, none of which any test,
 * mutation run or workflow had seen.
 *
 * It drives the same `SeedOrchestrator` the panel drives, with the same
 * validator, plan builder, field mapper and reference linker, and writes
 * through the same REST batching. What it leaves out is what the panel adds
 * around a run: progress posted to a webview, the AI field generator (the
 * faker fallback covers every rule on its own) and grappe partitioning.
 *
 * Usage:
 *   pnpm exec tsx packages/extension/cli/sandforge-seed.ts \
 *     --target TGT --template prebuilt-minimal-demo
 *
 * Run from the repository root of a checkout, after pnpm install and
 * pnpm build:shared.
 */

import type { SeedTemplate } from '@sandforge/shared';
import {
  PREBUILT_SEED_TEMPLATES,
  defaultFakerMethod,
  duplicateRuleHeaders,
} from '@sandforge/shared';
import { loadOrg, makeConn } from './sfSession.js';
import { SeedOrchestrator } from '../src/modules/seed/SeedOrchestrator.js';
import { SeedValidator } from '../src/modules/seed/SeedValidator.js';
import { DataPlanBuilder } from '../src/modules/seed/DataPlanBuilder.js';
import { FieldMapper } from '../src/modules/seed/FieldMapper.js';
import { ReferenceLinker } from '../src/modules/seed/ReferenceLinker.js';
import { FakerFallback } from '../src/modules/seed/FakerFallback.js';
import { AIDataGenerator } from '../src/modules/seed/AIDataGenerator.js';

const HELP = `sandforge-seed — fill an org from a seed template, without the editor.

Usage:
  pnpm exec tsx packages/extension/cli/sandforge-seed.ts \\
    --target <alias> [--template <id> | --object <ApiName>:<count>] [options]

Required:
  --target <alias>       sf CLI alias of the org to fill

One of:
  --template <id>        a built-in template; --list-templates names them
  --object <Api>:<n>     an object and how many rows; repeat for more, in
                         insert order. Fields are generated by the faker.

Options:
  --list-templates       name the built-in templates, then stop
  --batch-size <n>       records per write call            (default: 200)
  --dry-run              build and map, write nothing      (default: off)
  --json                 emit the run summary as JSON      (default: off)
  --help                 this text

Exit codes: 0 the run finished (read the summary for per-object failures),
1 the run could not be started, 2 a bad command line.
`;

/** Everything the command line settled. */
interface CliArgs {
  target: string;
  templateId?: string;
  objects: Array<{ objectApiName: string; recordCount: number }>;
  batchSize: number;
  dryRun: boolean;
  json: boolean;
}

/** SObject API name — letter-prefixed, alphanumeric and underscore. */
const API_NAME_RE = /^[A-Za-z][A-Za-z0-9_]{0,79}$/;

/** Read the command line, or explain why it cannot be read. */
export function parseArgs(argv: string[]): CliArgs {
  const args = argv.slice(2);
  if (args.includes('--help') || args.includes('-h')) {
    process.stdout.write(HELP);
    process.exit(0);
  }
  if (args.includes('--list-templates')) {
    for (const template of PREBUILT_SEED_TEMPLATES) {
      process.stdout.write(
        `${template.id.padEnd(34)}${template.objects.length} object(s)  ${template.name}\n`,
      );
    }
    process.exit(0);
  }
  const get = (flag: string, fallback?: string): string | undefined => {
    const at = args.indexOf(flag);
    return at >= 0 && at + 1 < args.length ? args[at + 1] : fallback;
  };
  const collect = (flag: string): string[] => {
    const out: string[] = [];
    for (let i = 0; i < args.length; i++) {
      if (args[i] === flag && i + 1 < args.length) out.push(args[i + 1]);
    }
    return out;
  };

  const target = get('--target');
  const templateId = get('--template');
  const rawObjects = collect('--object');
  if (!target) {
    process.stderr.write('Missing --target. Run with --help.\n');
    process.exit(2);
  }
  if (!templateId && rawObjects.length === 0) {
    process.stderr.write('Nothing to seed: give --template or --object. Run with --help.\n');
    process.exit(2);
  }
  if (templateId && rawObjects.length > 0) {
    // Two answers to "what should this write" is one too many.
    process.stderr.write('Give --template or --object, not both.\n');
    process.exit(2);
  }

  const objects = rawObjects.map((raw) => {
    const at = raw.lastIndexOf(':');
    const objectApiName = at > 0 ? raw.slice(0, at) : raw;
    const recordCount = at > 0 ? Number(raw.slice(at + 1)) : NaN;
    if (!API_NAME_RE.test(objectApiName)) {
      process.stderr.write(`Not an SObject API name: "${objectApiName}"\n`);
      process.exit(2);
    }
    if (!Number.isInteger(recordCount) || recordCount < 1 || recordCount > 100_000) {
      process.stderr.write(`--object wants "Name:<count>", not "${raw}".\n`);
      process.exit(2);
    }
    return { objectApiName, recordCount };
  });

  const batchSize = Number(get('--batch-size', '200') ?? '200');
  if (!Number.isInteger(batchSize) || batchSize < 1 || batchSize > 10_000) {
    process.stderr.write('--batch-size takes a whole number between 1 and 10000.\n');
    process.exit(2);
  }

  return {
    target,
    templateId,
    objects,
    batchSize,
    dryRun: args.includes('--dry-run'),
    json: args.includes('--json'),
  };
}

/** A built-in template by id, or `null` when the flags describe the objects. */
export function prebuiltTemplate(templateId: string | undefined): SeedTemplate | null {
  if (!templateId) return null;
  const found = PREBUILT_SEED_TEMPLATES.find((t) => t.id === templateId);
  if (!found) {
    const names = PREBUILT_SEED_TEMPLATES.map((t) => t.id).join(', ');
    process.stderr.write(`No template "${templateId}". There is: ${names}\n`);
    process.exit(2);
  }
  return found;
}

/**
 * The fields to fill for an object, and what to fill them with.
 *
 * An object with no field rules writes nothing — the validator refuses it now
 * — so `--object Name:count` has to name some. They come from the target's own
 * describe, through the same `defaultFakerMethod` the panel offers, so what
 * this writes is what the panel would write for the same object.
 *
 * Only what the platform insists on, plus `Name`: a seed is meant to make an
 * org usable, not to fill every column it has.
 */
export function rulesFromDescribe(
  fields: Array<{
    name: string;
    type: string;
    createable: boolean;
    nillable: boolean;
    defaultedOnCreate?: boolean;
  }>,
): SeedTemplate['objects'][number]['fieldRules'] {
  const wanted = fields.filter(
    (f) => f.createable && (f.name === 'Name' || (!f.nillable && f.defaultedOnCreate !== true)),
  );
  const rules: SeedTemplate['objects'][number]['fieldRules'] = [];
  for (const field of wanted) {
    const method = defaultFakerMethod(field.type, field.name);
    if (!method) continue;
    rules.push({
      fieldApiName: field.name,
      fieldType: field.type,
      ruleType: 'faker',
      config: { fakerMethod: method },
    });
  }
  return rules;
}

/** Run one seed from the given command line; exported so its parsing can be tested. */
export async function main(argv: string[] = process.argv): Promise<void> {
  const t0 = Date.now();
  const args = parseArgs(argv);
  const log = (line: string): void => {
    if (!args.json) process.stdout.write(`${line}\n`);
  };

  log(`sandforge-seed  -> ${args.target}`);
  const conn = makeConn(loadOrg(args.target));

  const now = new Date().toISOString();
  let template = prebuiltTemplate(args.templateId);
  if (!template) {
    const objects: SeedTemplate['objects'] = [];
    for (const [index, spec] of args.objects.entries()) {
      const described = await conn.sobject(spec.objectApiName).describe();
      const rules = rulesFromDescribe(
        described.fields as unknown as Parameters<typeof rulesFromDescribe>[0],
      );
      log(`  ${spec.objectApiName}: ${rules.map((r) => r.fieldApiName).join(', ') || '(none)'}`);
      objects.push({
        objectApiName: spec.objectApiName,
        recordCount: spec.recordCount,
        fieldRules: rules,
        excludedFields: [],
        insertOrder: index,
        batchSize: args.batchSize,
      });
    }
    template = {
      id: `cli-${Date.now()}`,
      name: 'sandforge-seed',
      description: 'Headless run',
      version: 1,
      strategy: 'faker',
      objects,
      tags: ['cli'],
      createdAt: now,
      updatedAt: now,
    };
  }
  log(`template: ${template.name} (${template.objects.length} object(s))`);

  const insert = async (
    _orgId: string,
    objectApiName: string,
    records: Record<string, unknown>[],
    batchSize: number,
  ): Promise<{ successIds: string[]; errors: string[] }> => {
    if (args.dryRun) {
      log(`  [dry-run] ${objectApiName}: ${records.length} record(s)`);
      return { successIds: records.map((_, i) => `dry-${i}`), errors: [] };
    }
    const successIds: string[] = [];
    const errors: string[] = [];
    for (let at = 0; at < records.length; at += batchSize) {
      const batch = records.slice(at, at + batchSize);
      const written = (await conn
        .sobject(objectApiName)
        .create(batch, { headers: duplicateRuleHeaders(true) })) as Array<{
        success: boolean;
        id?: string;
        errors?: Array<{ message: string }>;
      }>;
      for (const one of written) {
        if (one.success && one.id) successIds.push(one.id);
        else errors.push(one.errors?.[0]?.message ?? 'Unknown insert error');
      }
    }
    log(`  ${objectApiName}: ${successIds.length} written, ${errors.length} refused`);
    return { successIds, errors };
  };

  const creatableByObject = new Map<string, ReadonlySet<string>>();

  const orchestrator = new SeedOrchestrator({
    validator: new SeedValidator(),
    describeCreateableFields: async (objectApiName) => {
      const cached = creatableByObject.get(objectApiName);
      if (cached) return cached;
      const described = await conn.sobject(objectApiName).describe();
      const names = new Set(described.fields.filter((f) => f.createable).map((f) => f.name));
      creatableByObject.set(objectApiName, names);
      return names;
    },
    planBuilder: new DataPlanBuilder(),
    // An AI generator that refuses. The faker answers every rule the templates
    // here carry, and a run that needs an API key is a run nobody can
    // reproduce — but a template written elsewhere may carry an `ai` rule, and
    // silently filling those with something else would be worse than saying so.
    fieldMapper: new FieldMapper({
      aiGenerator: new AIDataGenerator(() => {
        throw new Error(
          'This template has an AI field rule. sandforge-seed runs without an ' +
            'AI key: use the panel for it, or replace the rule with a faker one.',
        );
      }),
      fakerFallback: new FakerFallback(),
    }),
    referenceLinker: new ReferenceLinker(),
    insert,
    generateId: () => `cli-${Math.random().toString(36).slice(2)}`,
    now: () => new Date().toISOString(),
  });

  log(args.dryRun ? '\nexecuting… (DRY-RUN)' : '\nexecuting… (REAL)');
  const result = await orchestrator.execute(template, args.target);
  const elapsedMs = Date.now() - t0;

  if (args.json) {
    process.stdout.write(
      `${JSON.stringify({ tool: 'sandforge-seed', target: args.target, dryRun: args.dryRun, result, elapsedMs }, null, 2)}\n`,
    );
    return;
  }

  log(`\nstatus:  ${String((result as { status?: string }).status ?? 'unknown')}`);
  log(`created: ${String((result as { totalRecordsCreated?: number }).totalRecordsCreated ?? 0)}`);
  for (const entry of result.objectResults ?? []) {
    log(`  ${entry.objectApiName}: ${entry.recordsCreated} created, ${entry.recordsFailed} failed`);
    for (const error of (entry.errors ?? []).slice(0, 3)) log(`      ${error}`);
  }
  log(`\ndone in ${elapsedMs}ms`);
}

// `tsx` runs this file directly; the check keeps it silent under test.
if (process.argv[1]?.includes('sandforge-seed')) {
  main().catch((err: unknown) => {
    process.stderr.write(`${err instanceof Error ? err.message : String(err)}\n`);
    process.exit(1);
  });
}
