import React, { useCallback } from 'react';
import { useFileSave } from '../../../hooks/useFileSave';
import { useTranslation } from 'react-i18next';
import type {
  ComplianceFrameworkType,
  ComplianceReport as ComplianceReportData,
} from '@sandforge/shared';
import { useBridgeQuery } from '../../../hooks/useBridgeQuery';
import { ErrorBanner } from '../../../components/ui/ErrorBanner';
import { Button } from '../../../components/ui/Button';
import { ComplianceTimeline } from './ComplianceTimeline';

/** Display labels for compliance frameworks (acronyms, locale-independent). */
const FRAMEWORK_LABELS: Record<ComplianceFrameworkType, string> = {
  gdpr: 'GDPR',
  ccpa: 'CCPA',
  hipaa: 'HIPAA',
  pci_dss: 'PCI-DSS',
  custom: 'Custom',
  none: 'None',
};

/**
 * Compliance report fetched from the extension (`autopilot:compliance-report`)
 * after an autopilot run. Shows the real anonymization entries generated by
 * the orchestrator — no store-derived demo data.
 */
export const ComplianceReport: React.FC = () => {
  const { save } = useFileSave();
  const { t } = useTranslation();
  // The handler answers with the report inside an envelope — `{ report }` —
  // which is what `AutopilotComplianceReportReady` declares. Reading the
  // payload as the report itself crashed the panel on open: `report.entries`
  // was `undefined`, and the whole thing landed in the ErrorBoundary as
  // "Something went wrong". The component test never saw it because it mocks
  // `useBridgeQuery` and hands it an already-unwrapped report.
  const { data, loading, error, refetch } = useBridgeQuery<{ report: ComplianceReportData }>(
    'autopilot:compliance-report',
    undefined,
    {
      responseType: 'autopilot:compliance-report',
      errorType: 'autopilot:error',
      timeoutMs: 60_000,
    },
  );
  const report = data?.report;

  /** Export the fetched report as JSON. */
  const handleExportJson = useCallback((): void => {
    if (!report) return;
    // Saved by the host: a webview is sandboxed without `allow-downloads`, so
    // the detached-anchor click this replaces frequently wrote nothing.
    save(`compliance-report-${Date.now()}.json`, JSON.stringify(report, null, 2), ['json']);
  }, [report, save]);

  if (loading) {
    return (
      <div
        className="flex items-center justify-center py-12 text-sm text-text-secondary"
        data-testid="compliance-report-loading"
      >
        {t('common.loading')}
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="flex flex-col gap-3 p-4" data-testid="compliance-report-error">
        <ErrorBanner message={error ?? t('common.noData')} />
        <div>
          <Button variant="secondary" size="sm" onClick={refetch} data-testid="compliance-retry">
            {t('common.retry')}
          </Button>
        </div>
      </div>
    );
  }

  const frameworkLabel =
    report.framework === 'none' ? t('autopilot.step3.none') : FRAMEWORK_LABELS[report.framework];

  return (
    <div className="flex flex-col gap-4 p-4" data-testid="compliance-report">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h3 className="text-base font-semibold text-text-primary">{t('autopilot.report.title')}</h3>
        <button
          className="px-3 py-1.5 text-xs font-medium rounded bg-[var(--sf-button-bg)] text-[var(--sf-button-fg)] hover:bg-[var(--sf-button-hover)] transition-colors"
          onClick={handleExportJson}
          data-testid="compliance-export-json"
        >
          {t('autopilot.report.exportJson')}
        </button>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
        <div className="flex flex-col gap-0.5 p-3 rounded bg-[var(--sf-bg-primary)]">
          <span className="text-[10px] uppercase tracking-wider text-text-secondary">
            {t('autopilot.report.framework')}
          </span>
          <span className="text-sm font-semibold text-text-primary" data-testid="report-framework">
            {frameworkLabel}
          </span>
        </div>
        <div className="flex flex-col gap-0.5 p-3 rounded bg-[var(--sf-bg-primary)]">
          <span className="text-[10px] uppercase tracking-wider text-text-secondary">
            {t('autopilot.report.status')}
          </span>
          <span className="text-sm font-semibold text-text-primary" data-testid="report-status">
            {t(`autopilot.report.${report.overallStatus}`)}
          </span>
        </div>
        <div className="flex flex-col gap-0.5 p-3 rounded bg-[var(--sf-bg-primary)]">
          <span className="text-[10px] uppercase tracking-wider text-text-secondary">
            {t('autopilot.report.piiDetected')}
          </span>
          <span className="text-sm font-semibold text-text-primary">
            {report.piiFieldsDetected}
          </span>
        </div>
        <div className="flex flex-col gap-0.5 p-3 rounded bg-[var(--sf-bg-primary)]">
          <span className="text-[10px] uppercase tracking-wider text-text-secondary">
            {t('autopilot.report.piiAnonymized')}
          </span>
          <span className="text-sm font-semibold text-text-primary">
            {report.piiFieldsAnonymized}
          </span>
        </div>
      </div>

      {/* Entries table */}
      <div className="rounded border border-[var(--sf-border)] overflow-hidden">
        <table className="w-full text-xs" data-testid="compliance-rules-table">
          <thead>
            <tr className="bg-[var(--sf-bg-primary)] text-left text-text-secondary">
              <th className="py-2 px-3 font-medium">{t('autopilot.report.object')}</th>
              <th className="py-2 px-3 font-medium">{t('autopilot.report.field')}</th>
              <th className="py-2 px-3 font-medium">{t('autopilot.report.category')}</th>
              <th className="py-2 px-3 font-medium">{t('autopilot.report.method')}</th>
              <th className="py-2 px-3 font-medium">{t('autopilot.report.recordsAnonymized')}</th>
              <th className="py-2 px-3 font-medium">{t('autopilot.report.rule')}</th>
            </tr>
          </thead>
          <tbody>
            {report.entries.length === 0 ? (
              <tr>
                <td colSpan={6} className="py-4 text-center text-text-secondary">
                  {t('common.noData')}
                </td>
              </tr>
            ) : (
              report.entries.map((entry) => (
                <tr
                  key={`${entry.objectApiName}-${entry.fieldApiName}`}
                  className="border-t border-[var(--sf-border)]"
                >
                  <td className="py-1.5 px-3 text-text-primary">{entry.objectApiName}</td>
                  <td className="py-1.5 px-3 text-text-primary">{entry.fieldApiName}</td>
                  <td className="py-1.5 px-3 text-text-primary">{entry.piiCategory}</td>
                  <td className="py-1.5 px-3 text-text-primary">{entry.anonymizationMethod}</td>
                  <td className="py-1.5 px-3 text-text-primary tabular-nums">
                    {entry.recordsAnonymized.toLocaleString()}
                  </td>
                  <td className="py-1.5 px-3 text-text-primary">{entry.ruleApplied}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Timeline */}
      <div>
        <h4 className="text-sm font-semibold text-text-primary mb-2">
          {t('autopilot.report.title')} — Timeline
        </h4>
        <ComplianceTimeline />
      </div>
    </div>
  );
};
